name: Build and Push Docker Container

on:
  push:
    branches:
      - "release"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/memebot:latest

  lines-of-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lines of Code Reporter
        uses: PavanMudigonda/lines-of-code-reporter@v1.6
        with:
          directory: ${{ github.workspace }} # Optional: Defaults to workspace
          exclude_dir: .git,node_modules,vendor # Exclude unnecessary directories
          exclude_lang: # Optional: Specify languages to exclude
          exclude_ext: # Optional: Specify extensions to exclude
          include_lang: # Optional: Specify languages to include
          include_ext: # Optional: Specify extensions to include
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required for authentication
          skip_check_run: false # Optional: Set to true to disable check runs
